### ISSUE TITLE
from future import standard_library ImportError: No module named future

### ISSUE THREAD

**Issue by Tabrijix86** [Intelligent-Quads/iq_tutorials#60]
tabriji@tabriji-hp:~/ardupilot/ArduCopter$ sim_vehicle.py 
Traceback (most recent call last):
  File "/home/tabriji/ardupilot/Tools/autotest/sim_vehicle.py", line 25, in <module>
    from pymavlink import mavextra
ImportError: No module named pymavlink
tabriji@tabriji-hp:~/ardupilot/ArduCopter$ python3 sim_vehicle.py 
python3: can't open file '/home/tabriji/ardupilot/ArduCopter/sim_vehicle.py': [Errno 2] No such file or directory
tabriji@tabriji-hp:~/ardupilot/ArduCopter$ python3 ../Tools/autotest/sim_vehicle.py 
SIM_VEHICLE: Start
SIM_VEHICLE: Killing tasks
SIM_VEHICLE: Starting up at SITL location
SIM_VEHICLE: WAF build
SIM_VEHICLE: Configure waf
SIM_VEHICLE: "/home/tabriji/ardupilot/modules/waf/waf-light" "configure" "--board" "sitl"
Setting top to                           : /home/tabriji/ardupilot 
Setting out to                           : /home/tabriji/ardupilot/build 
Autoconfiguration                        : enabled 
Setting board to                         : sitl 
Using toolchain                          : native 
Checking for 'g++' (C++ compiler)        : /usr/lib/ccache/g++ 
Checking for 'gcc' (C compiler)          : /usr/lib/ccache/gcc 
Checking for c flags '-MMD'              : yes 
Checking for cxx flags '-MMD'            : yes 
Checking for need to link with librt     : not necessary 
Checking for feenableexcept              : yes 
Checking for HAVE_CMATH_ISFINITE         : yes 
Checking for HAVE_CMATH_ISINF            : yes 
Checking for HAVE_CMATH_ISNAN            : yes 
Checking for NEED_CMATH_ISFINITE_STD_NAMESPACE : yes 
Checking for NEED_CMATH_ISINF_STD_NAMESPACE    : yes 
Checking for NEED_CMATH_ISNAN_STD_NAMESPACE    : yes 
Checking for header endian.h                   : yes 
Checking for header byteswap.h                 : yes 
Checking for HAVE_MEMRCHR                      : yes 
Checking for program 'python'                  : /usr/bin/python 
Checking for python version >= 2.7.0           : 2.7.18 
Checking for program 'python'                  : /usr/bin/python 
Checking for python version >= 2.7.0           : 2.7.18 
Source is git repository                       : yes 
Update submodules                              : yes 
Checking for program 'git'                     : /usr/bin/git 
Checking for program 'size'                    : /usr/bin/size 
Benchmarks                                     : disabled 
Unit tests                                     : enabled 
Scripting                                      : enabled 
Scripting runtime checks                       : enabled 
Checking for program 'rsync'                   : /usr/bin/rsync 
'configure' finished successfully (0.558s)
SIM_VEHICLE: Building
SIM_VEHICLE: "/home/tabriji/ardupilot/modules/waf/waf-light" "build" "--target" "bin/arducopter"
Waf: Entering directory `/home/tabriji/ardupilot/build/sitl'
Embedding file sandbox.lua:libraries/AP_Scripting/scripts/sandbox.lua
[3/4] Processing modules/mavlink/message_definitions/v1.0/ardupilotmega.xml
[4/4] Creating build/sitl/ap_version.h
Waf: Leaving directory `/home/tabriji/ardupilot/build/sitl'
Build failed
Traceback (most recent call last):
  File "/home/tabriji/ardupilot/modules/waf/waflib/Task.py", line 338, in process
    ret = self.run()
  File "Tools/ardupilotwaf/mavgen.py", line 55, in run
    from pymavlink.generator import mavgen
  File "/home/tabriji/ardupilot/modules/mavlink/pymavlink/generator/mavgen.py", line 12, in <module>
    from future import standard_library
ImportError: No module named future

SIM_VEHICLE: Build failed
SIM_VEHICLE: Killing tasks
tabriji@tabriji-hp:~/ardupilot/ArduCopter$ pip3 install -U future
Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: future in /home/tabriji/.local/lib/python3.10/site-packages (1.0.0)
tabriji@tabriji-hp:~/ardupilot/ArduCopter$ pip install -U future
Defaulting to user installation because normal site-packages is not writeable
tabriji@tabriji-hp:~/ardupilot/ArduCopter$ python3 sim_vehicle.py 
python3: can't open file '/home/tabriji/ardupilot/ArduCopter/sim_vehicle.py': [Errno 2] No such file or directory
tabriji@tabriji-hp:~/ardupilot/ArduCopter$ ls
afs_copter.cpp            avoidance_adsb.cpp      esc_calibration.cpp  landing_gear.cpp     mode_brake.cpp         mode_loiter.cpp          motor_test.cpp         standby.cpp           UserVariables.h
afs_copter.h              avoidance_adsb.h        events.cpp           leds.cpp             mode_circle.cpp        mode_poshold.cpp         navigation.cpp         surface_tracking.cpp  version.cpp
AP_Arming.cpp             baro_ground_effect.cpp  failsafe.cpp         Log.cpp              mode.cpp               mode_rtl.cpp             Parameters.cpp         system.cpp            version.h
AP_Arming.h               commands.cpp            fence.cpp            Makefile.waf         mode_drift.cpp         mode_smart_rtl.cpp       Parameters.h           takeoff.cpp           wscript
APM_Config.h              compassmot.cpp          GCS_Copter.cpp       mode_acro.cpp        mode_flip.cpp          mode_sport.cpp           precision_landing.cpp  terrain.cpp
APM_Config_mavlink_hil.h  config.h                GCS_Copter.h         mode_acro_heli.cpp   mode_flowhold.cpp      mode_stabilize.cpp       radio.cpp              toy_mode.cpp
AP_Rally.cpp              Copter.cpp              GCS_Mavlink.cpp      mode_althold.cpp     mode_follow.cpp        mode_stabilize_heli.cpp  RC_Channel.cpp         toy_mode.h
AP_Rally.h                Copter.h                GCS_Mavlink.h        mode_auto.cpp        mode_guided.cpp        mode_systemid.cpp        RC_Channel.h           tuning.cpp
AP_State.cpp              crash_check.cpp         heli.cpp             mode_autorotate.cpp  mode_guided_nogps.cpp  mode_throw.cpp           ReleaseNotes.txt       UserCode.cpp
Attitude.cpp              defines.h               inertia.cpp          mode_autotune.cpp    mode.h                 mode_zigzag.cpp          sensors.cpp            UserParameters.cpp
autoyaw.cpp               ekf_check.cpp           land_detector.cpp    mode_avoid_adsb.cpp  mode_land.cpp          motors.cpp               setup.cpp              UserParameters.h
tabriji@tabriji-hp:~/ardupilot/ArduCopter$ ../Tools/autotest/sim_vehicle.py
Traceback (most recent call last):
  File "../Tools/autotest/sim_vehicle.py", line 25, in <module>
    from pymavlink import mavextra
ImportError: No module named pymavlink
tabriji@tabriji-hp:~/ardupilot/ArduCopter$ 

![Screenshot from 2024-03-19 13-16-53](https://github.com/Intelligent-Quads/iq_tutorials/assets/95961672/9b3050f5-8e69-4b5a-b9b9-c44c150a16cf)
![Screenshot from 2024-03-19 13-17-09](https://github.com/Intelligent-Quads/iq_tutorials/assets/95961672/23268a4e-8684-4bfb-8c5d-0dbf886cd865)

**Comment by Tabrijix86** [comment]
![Screenshot from 2024-03-19 13-35-29](https://github.com/Intelligent-Quads/iq_tutorials/assets/95961672/7cbbaf75-eb11-46e3-b10e-40e89bbd0eab)
